/* SPDX-License-Identifier: BSD-2-Clause */
/*
 * Copyright (c) 2018, Linaro Limited
 */

#ifndef __SKS_TA_COMPAT_H__
#define __SKS_TA_COMPAT_H__

#define sks_ck_slot_info		sks_slot_info

#define SKS_TOKEN_PRESENT		SKS_CKFS_TOKEN_PRESENT
#define SKS_TOKEN_REMOVABLE		SKS_CKFS_REMOVABLE_DEVICE
#define SKS_TOKEN_HW			SKS_CKFS_HW_SLOT

#define sks_ck_token_info		sks_token_info

#define SKS_TOKEN_HAS_RNG		SKS_CKFT_RNG
#define SKS_TOKEN_IS_READ_ONLY		SKS_CKFT_WRITE_PROTECTED
#define SKS_TOKEN_REQUIRE_LOGIN		SKS_CKFT_LOGIN_REQUIRED
#define SKS_TOKEN_HAS_USER_PIN		SKS_CKFT_USER_PIN_INITIALIZED
#define SKS_TOKEN_FULLY_RESTORABLE	SKS_CKFT_RESTORE_KEY_NOT_NEEDED
#define SKS_TOKEN_HAS_CLOCK		SKS_CKFT_CLOCK_ON_TOKEN
#define SKS_TOKEN_ALT_AUTHENT		SKS_CKFT_PROTECTED_AUTHENTICATION_PATH
#define SKS_TOKEN_CAN_DUAL_PROC		SKS_CKFT_DUAL_CRYPTO_OPERATIONS
#define SKS_TOKEN_INITED		SKS_CKFT_TOKEN_INITIALIZED
#define SKS_TOKEN_USR_PIN_FAILURE	SKS_CKFT_USER_PIN_COUNT_LOW
#define SKS_TOKEN_USR_PIN_LAST		SKS_CKFT_USER_PIN_FINAL_TRY
#define SKS_TOKEN_USR_PIN_LOCKED	SKS_CKFT_USER_PIN_LOCKED
#define SKS_TOKEN_USR_PIN_TO_CHANGE	SKS_CKFT_USER_PIN_TO_BE_CHANGED
#define SKS_TOKEN_SO_PIN_FAILURE	SKS_CKFT_SO_PIN_COUNT_LOW
#define SKS_TOKEN_SO_PIN_LAST		SKS_CKFT_SO_PIN_FINAL_TRY
#define SKS_TOKEN_SO_PIN_LOCKED		SKS_CKFT_SO_PIN_LOCKED
#define SKS_TOKEN_SO_PIN_TO_CHANGE	SKS_CKFT_SO_PIN_TO_BE_CHANGED
#define SKS_TOKEN_BAD_STATE		SKS_CKFT_ERROR_STATE

#define sks_ck_mecha_info		sks_mechanism_info

#define SKS_PROC_HW			SKS_CKFM_HW
#define SKS_PROC_ENCRYPT		SKS_CKFM_ENCRYPT
#define SKS_PROC_DECRYPT		SKS_CKFM_DECRYPT
#define SKS_PROC_DIGEST			SKS_CKFM_DIGEST
#define SKS_PROC_SIGN			SKS_CKFM_SIGN
#define SKS_PROC_SIGN_RECOVER		SKS_CKFM_SIGN_RECOVER
#define SKS_PROC_VERIFY			SKS_CKFM_VERIFY
#define SKS_PROC_VERFIY_RECOVER		SKS_CKFM_VERIFY_RECOVER
#define SKS_PROC_GENERATE		SKS_CKFM_GENERATE
#define SKS_PROC_GENERATE_PAIR		SKS_CKFM_GENERATE_PAIR
#define SKS_PROC_WRAP			SKS_CKFM_WRAP
#define SKS_PROC_UNWRAP			SKS_CKFM_UNWRAP
#define SKS_PROC_DERIVE			SKS_CKFM_DERIVE

#define sks_ck_session_info		sks_session_info

#ifndef SKS_OK
#define SKS_OK				SKS_CKR_OK
#define SKS_ERROR			SKS_CKR_GENERAL_ERROR
#define SKS_MEMORY			SKS_CKR_DEVICE_MEMORY
#define SKS_BAD_PARAM			SKS_CKR_ARGUMENT_BAD
#define SKS_SHORT_BUFFER		SKS_CKR_BUFFER_TOO_SMALL
#define SKS_FAILED			SKS_CKR_FUNCTION_FAILED
#endif
#define SKS_VERIFY_FAILED		SKS_CKR_SIGNATURE_INVALID
#define SKS_INVALID_ATTRIBUTES		SKS_CKR_TEMPLATE_INCONSISTENT
#define SKS_INVALID_TYPE		SKS_CKR_ATTRIBUTE_TYPE_INVALID
#define SKS_INVALID_VALUE		SKS_CKR_ATTRIBUTE_VALUE_INVALID
#define SKS_INVALID_OBJECT		SKS_CKR_OBJECT_HANDLE_INVALID
#define SKS_INVALID_KEY			SKS_CKR_KEY_HANDLE_INVALID
#define SKS_INVALID_PROC		SKS_CKR_MECHANISM_INVALID
#define SKS_INVALID_SESSION		SKS_CKR_SESSION_HANDLE_INVALID
#define SKS_INVALID_SLOT		SKS_CKR_SLOT_ID_INVALID
#define SKS_INVALID_PROC_PARAM		SKS_CKR_MECHANISM_PARAM_INVALID
#define SKS_PIN_INCORRECT		SKS_CKR_PIN_INCORRECT
#define SKS_PIN_LOCKED			SKS_CKR_PIN_LOCKED
#define SKS_PIN_EXPIRED			SKS_CKR_PIN_EXPIRED
#define SKS_PIN_INVALID			SKS_CKR_PIN_INVALID
#define SKS_CK_SESSION_PENDING		SKS_CKR_SESSION_EXISTS
#define SKS_CK_SESSION_IS_READ_ONLY	SKS_CKR_SESSION_READ_ONLY
#define SKS_CK_SO_IS_LOGGED_READ_WRITE	SKS_CKR_SESSION_READ_WRITE_SO_EXISTS
#define SKS_PROCESSING_ACTIVE		SKS_CKR_OPERATION_ACTIVE
#define SKS_CK_NOT_PERMITTED		SKS_CKR_KEY_FUNCTION_NOT_PERMITTED
#define SKS_PROCESSING_INACTIVE		SKS_CKR_OPERATION_NOT_INITIALIZED

#define SKS_PERSISTENT_SHIFT		0
#define SKS_NEED_AUTHEN_SHIFT		1
#define SKS_TRUSTED_SHIFT		2
#define SKS_SENSITIVE_SHIFT		3
#define SKS_ENCRYPT_SHIFT		4
#define SKS_DECRYPT_SHIFT		5
#define SKS_WRAP_SHIFT			6
#define SKS_UNWRAP_SHIFT		7
#define SKS_SIGN_SHIFT			8
#define SKS_SIGN_RECOVER_SHIFT		9
#define SKS_VERIFY_SHIFT		10
#define SKS_VERIFY_RECOVER_SHIFT	11
#define SKS_DERIVE_SHIFT		12
#define SKS_EXTRACTABLE_SHIFT		13
#define SKS_LOCALLY_GENERATED_SHIFT	14
#define SKS_NEVER_EXTRACTABLE_SHIFT	15
#define SKS_ALWAYS_SENSITIVE_SHIFT	16
#define SKS_MODIFIABLE_SHIFT		17
#define SKS_COPYABLE_SHIFT		18
#define SKS_DESTROYABLE_SHIFT		19
#define SKS_ALWAYS_AUTHEN_SHIFT		20
#define SKS_WRAP_FROM_TRUSTED_SHIFT	21
#define SKS_BOOLPROP_LAST_SHIFT		21

#define SKS_BOOLPROPS_TEST \
	(SKS_PERSISTENT_SHIFT - SKS_CKA_TOKEN) || \
	(SKS_NEED_AUTHEN_SHIFT - SKS_CKA_PRIVATE) || \
	(SKS_TRUSTED_SHIFT - SKS_CKA_TRUSTED) || \
	(SKS_SENSITIVE_SHIFT - SKS_CKA_SENSITIVE) || \
	(SKS_ENCRYPT_SHIFT - SKS_CKA_ENCRYPT) || \
	(SKS_DECRYPT_SHIFT - SKS_CKA_DECRYPT) || \
	(SKS_WRAP_SHIFT - SKS_CKA_WRAP) || \
	(SKS_UNWRAP_SHIFT - SKS_CKA_UNWRAP) || \
	(SKS_SIGN_SHIFT - SKS_CKA_SIGN) || \
	(SKS_SIGN_RECOVER_SHIFT - SKS_CKA_SIGN_RECOVER) || \
	(SKS_VERIFY_SHIFT - SKS_CKA_VERIFY) || \
	(SKS_VERIFY_RECOVER_SHIFT - SKS_CKA_VERIFY_RECOVER) || \
	(SKS_DERIVE_SHIFT - SKS_CKA_DERIVE) || \
	(SKS_EXTRACTABLE_SHIFT - SKS_CKA_EXTRACTABLE) || \
	(SKS_LOCALLY_GENERATED_SHIFT - SKS_CKA_LOCAL) || \
	(SKS_NEVER_EXTRACTABLE_SHIFT - SKS_CKA_NEVER_EXTRACTABLE) || \
	(SKS_ALWAYS_SENSITIVE_SHIFT - SKS_CKA_ALWAYS_SENSITIVE) || \
	(SKS_MODIFIABLE_SHIFT - SKS_CKA_MODIFIABLE) || \
	(SKS_COPYABLE_SHIFT - SKS_CKA_COPYABLE) || \
	(SKS_DESTROYABLE_SHIFT - SKS_CKA_DESTROYABLE) || \
	(SKS_ALWAYS_AUTHEN_SHIFT - SKS_CKA_ALWAYS_AUTHENTICATE) || \
	(SKS_WRAP_FROM_TRUSTED_SHIFT - SKS_CKA_WRAP_WITH_TRUSTED)

#define SKS_BP_PERSISTENT		BIT(SKS_PERSISTENT_SHIFT)
#define SKS_BP_NEED_AUTHEN		BIT(SKS_NEED_AUTHEN_SHIFT)
#define SKS_BP_TRUSTED			BIT(SKS_TRUSTED_SHIFT)
#define SKS_BP_SENSITIVE		BIT(SKS_SENSITIVE_SHIFT)
#define SKS_BP_ENCRYPT			BIT(SKS_ENCRYPT_SHIFT)
#define SKS_BP_DECRYPT			BIT(SKS_DECRYPT_SHIFT)
#define SKS_BP_WRAP			BIT(SKS_WRAP_SHIFT)
#define SKS_BP_UNWRAP			BIT(SKS_UNWRAP_SHIFT)
#define SKS_BP_SIGN			BIT(SKS_SIGN_SHIFT)
#define SKS_BP_SIGN_RECOVER		BIT(SKS_SIGN_RECOVER_SHIFT)
#define SKS_BP_VERIFY			BIT(SKS_VERIFY_SHIFT)
#define SKS_BP_VERIFY_RECOVER		BIT(SKS_VERIFY_RECOVER_SHIFT)
#define SKS_BP_DERIVE			BIT(SKS_DERIVE_SHIFT)
#define SKS_BP_EXTRACTABLE		BIT(SKS_EXTRACTABLE_SHIFT)
#define SKS_BP_LOCALLY_GENERATED	BIT(SKS_LOCALLY_GENERATED_SHIFT)
#define SKS_BP_NEVER_EXTRACTABLE	BIT(SKS_NEVER_EXTRACTABLE_SHIFT)
#define SKS_BP_ALWAYS_SENSITIVE		BIT(SKS_ALWAYS_SENSITIVE_SHIFT)
#define SKS_BP_MODIFIABLE		BIT(SKS_MODIFIABLE_SHIFT)
#define SKS_BP_COPYABLE			BIT(SKS_COPYABLE_SHIFT)
#define SKS_BP_DESTROYABLE		BIT(SKS_DESTROYABLE_SHIFT)
#define SKS_BP_ALWAYS_AUTHEN		BIT(SKS_ALWAYS_AUTHEN_SHIFT)
#define SKS_BP_WRAP_FROM_TRUSTED	BIT(SKS_WRAP_FROM_TRUSTED_SHIFT)

#define sks_reference			sks_attribute_head

#define SKS_LABEL			SKS_CKA_LABEL
#define SKS_VALUE			SKS_CKA_VALUE
#define SKS_VALUE_LEN			SKS_CKA_VALUE_LEN
#define SKS_WRAP_ATTRIBS		SKS_CKA_WRAP_TEMPLATE
#define SKS_UNWRAP_ATTRIBS		SKS_CKA_UNWRAP_TEMPLATE
#define SKS_DERIVE_ATTRIBS		SKS_CKA_DERIVE_TEMPLATE
#define SKS_ACTIVATION_DATE		SKS_CKA_START_DATE
#define SKS_REVOKATION_DATE		SKS_CKA_END_DATE
#define SKS_OBJECT_ID			SKS_CKA_OBJECT_ID
#define SKS_APPLICATION_ID		SKS_CKA_APPLICATION
#define SKS_PROCESSING_ID		SKS_CKA_MECHANISM_TYPE
#define SKS_KEY_ID			SKS_CKA_ID
#define SKS_ALLOWED_PROCESSINGS		SKS_CKA_ALLOWED_MECHANISMS
#define SKS_CLASS			SKS_CKA_CLASS
#define SKS_TYPE			SKS_CKA_KEY_TYPE
#define SKS_PERSISTENT			SKS_CKA_TOKEN
#define SKS_NEED_AUTHEN			SKS_CKA_PRIVATE
#define SKS_TRUSTED			SKS_CKA_TRUSTED
#define SKS_SENSITIVE			SKS_CKA_SENSITIVE
#define SKS_ENCRYPT			SKS_CKA_ENCRYPT
#define SKS_DECRYPT			SKS_CKA_DECRYPT
#define SKS_WRAP			SKS_CKA_WRAP
#define SKS_UNWRAP			SKS_CKA_UNWRAP
#define SKS_SIGN			SKS_CKA_SIGN
#define SKS_SIGN_RECOVER		SKS_CKA_SIGN_RECOVER
#define SKS_VERIFY			SKS_CKA_VERIFY
#define SKS_VERIFY_RECOVER		SKS_CKA_VERIFY_RECOVER
#define SKS_DERIVE			SKS_CKA_DERIVE
#define SKS_EXTRACTABLE			SKS_CKA_EXTRACTABLE
#define SKS_LOCALLY_GENERATED		SKS_CKA_LOCAL
#define SKS_NEVER_EXTRACTABLE		SKS_CKA_NEVER_EXTRACTABLE
#define SKS_ALWAYS_SENSITIVE		SKS_CKA_ALWAYS_SENSITIVE
#define SKS_MODIFIABLE			SKS_CKA_MODIFIABLE
#define SKS_COPYABLE			SKS_CKA_COPYABLE
#define SKS_DESTROYABLE			SKS_CKA_DESTROYABLE
#define SKS_ALWAYS_AUTHEN		SKS_CKA_ALWAYS_AUTHENTICATE
#define SKS_WRAP_FROM_TRUSTED		SKS_CKA_WRAP_WITH_TRUSTED

#define SKS_OBJ_SYM_KEY				SKS_CKO_SECRET_KEY
#define SKS_OBJ_PUB_KEY				SKS_CKO_PUBLIC_KEY
#define SKS_OBJ_PRIV_KEY			SKS_CKO_PRIVATE_KEY
#define SKS_OBJ_OTP_KEY				SKS_CKO_OTP_KEY
#define SKS_OBJ_CERTIFICATE			SKS_CKO_CERTIFICATE
#define SKS_OBJ_RAW_DATA			SKS_CKO_DATA
#define SKS_OBJ_CK_DOMAIN_PARAMS		SKS_CKO_DOMAIN_PARAMETERS
#define SKS_OBJ_CK_HW_FEATURES			SKS_CKO_HW_FEATURE
#define SKS_OBJ_CK_MECHANISM			SKS_CKO_MECHANISM

#define SKS_KEY_AES				SKS_CKK_AES
#define SKS_GENERIC_SECRET			SKS_CKK_GENERIC_SECRET
#define SKS_KEY_HMAC_MD5			SKS_CKK_MD5_HMAC
#define SKS_KEY_HMAC_SHA1			SKS_CKK_SHA_1_HMAC
#define SKS_KEY_HMAC_SHA224			SKS_CKK_SHA224_HMAC
#define SKS_KEY_HMAC_SHA256			SKS_CKK_SHA256_HMAC
#define SKS_KEY_HMAC_SHA384			SKS_CKK_SHA384_HMAC
#define SKS_KEY_HMAC_SHA512			SKS_CKK_SHA512_HMAC

#define SKS_PROC_AES_ECB_NOPAD			SKS_CKM_AES_ECB
#define SKS_PROC_AES_CBC_NOPAD			SKS_CKM_AES_CBC
#define SKS_PROC_AES_CBC_PAD			SKS_CKM_AES_CBC_PAD
#define SKS_PROC_AES_CTS			SKS_CKM_AES_CTS
#define SKS_PROC_AES_CTR			SKS_CKM_AES_CTR
#define SKS_PROC_AES_GCM			SKS_CKM_AES_GCM
#define SKS_PROC_AES_CCM			SKS_CKM_AES_CCM
#define SKS_PROC_AES_GMAC			SKS_CKM_AES_GMAC
#define SKS_PROC_AES_CMAC			SKS_CKM_AES_CMAC
#define SKS_PROC_AES_CMAC_GENERAL		SKS_CKM_AES_CMAC_GENERAL
#define SKS_PROC_AES_DERIVE_BY_ECB		SKS_CKM_AES_ECB_ENCRYPT_DATA
#define SKS_PROC_AES_DERIVE_BY_CBC		SKS_CKM_AES_CBC_ENCRYPT_DATA
#define SKS_PROC_AES_GENERATE			SKS_CKM_AES_KEY_GEN
#define SKS_PROC_GENERIC_GENERATE		SKS_CKM_GENERIC_SECRET_KEY_GEN
#define SKS_PROC_HMAC_MD5			SKS_CKM_MD5_HMAC
#define SKS_PROC_HMAC_SHA1			SKS_CKM_SHA_1_HMAC
#define SKS_PROC_HMAC_SHA224			SKS_CKM_SHA224_HMAC
#define SKS_PROC_HMAC_SHA256			SKS_CKM_SHA256_HMAC
#define SKS_PROC_HMAC_SHA384			SKS_CKM_SHA384_HMAC
#define SKS_PROC_HMAC_SHA512			SKS_CKM_SHA512_HMAC
#define SKS_PROC_AES_CBC_MAC			SKS_CKM_AES_XCBC_MAC
#define SKS_PROC_RAW_IMPORT			SKS_PROCESSING_IMPORT
#define SKS_PROC_RAW_COPY			SKS_PROCESSING_COPY

#endif /*__SKS_TA_COMPAT_H__*/
