global-incdirs-y += include
global-incdirs-y += src
subdirs-y += src

CFG_SKS_TA_TOKEN_COUNT ?= 3
CPPFLAGS += -DCFG_SKS_TA_TOKEN_COUNT=$(CFG_SKS_TA_TOKEN_COUNT)

# Include configuration file generated by OP-TEE OS (CFG_* macros)
CPPFLAGS += -I $(TA_DEV_KIT_DIR)/host_include -include conf.h
